### ISSUE TITLE
Enhanced Tracking Protection Toolbar menu items don't respect Compact Mode

### ISSUE THREAD

**Issue by LordRishav** [black7375/Firefox-UI-Fix#101]
**Describe the bug**
The height of the menu items in the Enhanced Tracking Protection toolbar remains the same even when Compact Mode is turned on.

**Expected behavior**
The menu items in the ETP toolbar reduce in height just as all other menu items do.

**Screenshots**
[The current situation of ETP toolbar in Lepton with Compact Mode](https://i.imgur.com/6ku9d7k.png)
[Other menu items' height when compact mode is turned on](https://i.imgur.com/nXwYGr2.png)

**Environment (please complete the following information):**
Check like `- [x]`.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
 - Firefox Version: 89.0.1
 - OS:
   - [x] Linux
   - [ ] Windows
   - [ ] Mac
   - [ ] Others: 
 - Theme:
   - [ ] Light
   - [ ] Dark
   - [ ] Alpenglow(System: Light)
   - [ ] Alpenglow(System: Dark)
   - [x] System Default
     - GTK Theme Name(Only Linux User): Breeze Light

**Additional context**
N/A

**Comment by black7375** [comment]
It has been confirmed and will be fixed in the future.

**Comment by LordRishav** [comment]
It seems that the case is the same with the Downloads toolbar, it still has the same amount of padding even in Compact mode.

**Comment by SimYunSup** [comment]
![image](https://user-images.githubusercontent.com/47362439/124263797-abca9d00-db6e-11eb-8aef-ffb3c92f5bc2.png)
I think changing like this is what you want. Right?

**Comment by LordRishav** [comment]
@SimYunSup Yes, makes the UI more consistent when using Compact Mode. I would like to see this in Lepton. Thank you

**Comment by black7375** [comment]
The results of the investigation are hard-coded.
```css
#protections-popup-mainView-panel-header {
    min-height: 43.5px;
}
```

![image](https://user-images.githubusercontent.com/25581533/124338053-69688680-db95-11eb-86cf-1270dea68614.png)
..etc

If you submit a patch, I will merge it after testing.
