### ISSUE TITLE
Ver 3.0 Plan

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#109]
- [x] Proton style theme #48
- [x] Theme
  - [x] Light mode #24
  - [x] GTK Support #120
- [x] Color
  - [x] Context menu color #37
  - [x] Fully dark mode
    - [x] about:plugins
    - [x] about:cache
    - [x] about:checkerboard
    - [x] about:sync-log
    - [x] about:memory
    - [x] https://addons.mozilla.org
    - [x] https://support.mozilla.org
    - [x] https://accounts.firefox.com
    - [x] Download Popup
    - [x] Notification
- [x] Padding for compact mode
  - [x] Popup menu #101
  - [x] URL view #79
  - [x] Infobar
- [x] Install Script
  - [x] Port to powershell #119
  - [x] Update feature
  - [x] Librewolf #123

**Comment by black7375** [comment]
From now on, the versioning rules change in detail.

**Version**
- Semantic Versioning
- Rapid releases: We will release the feature as soon as it is complete, but the cycle should be 2-4 weeks.

---

Branch rules

**`master`**
- For release
- Minor features
- Bug patches

**`dev`**
- https://github.com/black7375/Firefox-UI-Fix/tree/dev
- For next version
- Major features
- Next version's minor features
