### ISSUE TITLE
[Meta] Miscellaneous layout bugs

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#175]
**Describe the bug**
These are known layout bugs that aren't considered critical to fix right away, but they are.

**Bug list**
- [x]  Height in compact mode still doesn't match original Photon(Windows8, Windows 10) https://github.com/black7375/Firefox-UI-Fix/issues/154#issuecomment-899972419
- [ ] Net tab button icon(`36x37` => `36x36`) https://github.com/black7375/Firefox-UI-Fix/pull/146#issuecomment-899101401
- [x] Favicon position https://www.reddit.com/r/FirefoxCSS/comments/p2ee0v/lepton_30_released/h9eaj4v/?context=3 https://github.com/black7375/Firefox-UI-Fix/commit/6b045e34019c147910d2ae20a080faaeb3c0ece5 
    ![image](https://user-images.githubusercontent.com/25581533/129911000-4bf61086-0203-476a-800c-d30fa166eeaf.png)

**Comment by black7375** [comment]
I think it can be closed.
