### ISSUE TITLE
Ver 4.5 Plan

### ISSUE THREAD

**Issue by black7375** [black7375/Firefox-UI-Fix#203]
**Why `v4.5`?**
All major features of `Stage 1 - Project Neutrino` in the roadmap(#2) have been developed. :clap: :clap: 

Therefore, before moving on to the next stage, it is a version to clean up things that were lacking and improve the level of perfection.
The goals are system color, dark mode enhancement, and wiki documentation.

**What comes in `v5.0`?**
It focuses on restoring page action and animation that are difficult with CSS alone.
- Restore page action button
- Restore bookmark animation
- Reveal Effect ([Fluent Tab Hover Effect](https://github.com/black7375/Firefox-UI-Fix/blob/interactive-js/JS/TabHoverEffect.uc.js))
- ..etc

**For Release**
- [x] System Theme
  - [x] Windows10 System Theme like Legacy Edge
  - [x] MacOS: Ref https://github.com/Tnings/MacosVibrant
- [x] Looks like Proton Elements
  - Ref: https://github.com/Guerra24/Firefox-UWP-Style
  - [x] Library Popup #57
  - [x] Common Dialog
  - [x] Edit CA Cert
  - [x] Cert exception
  - [x] Page Info
- [x] More Dark Mode
  - [x] Source View Darkmode
- [x] Animate
  - [x] Sound Tab
  - [x] Pinned Tab
  - [x] Hover Background (But, Can't apply at `treechildren::-moz-tree-row`)
  - [x] Arrow Open / Close (But, Can't apply at `treechildren::-moz-tree-twisty`)
  - [x] Sidebar
- [x] Tab
  - [x] Bottom Rounded Corner for GTK https://github.com/black7375/Firefox-UI-Fix/commit/83412170e552e5adfe14f93a15caa2ef42c78e3d
  - [x] Unloaded Tab to dimmed #258
- [x] Icons
  - [x] Resize fluent icons #213
  - [x] Version compatibility
  - [x] Mac's reload icons
  - [x] Reload Icon in Firefox 92 #217
- [x] Others
  - [x] Resize the Flexible Space in the toolbar #224

**For Wiki**
- [x] Tabs on bottom #34
- [ ] Accent Color #76 #202
- [ ] Pinned tab's close button
  - [ ] Active pinned tabs are wider than inactive ones #38 

**Not Sure**
- Windows installer with [WIX](https://wixtoolset.org/)
- Context menu looks like window at linux
- Addon dark mode
- UUID replacer scripts

**Comment by black7375** [comment]
I've been running for the past few months, I'm taking a break and trying to find information about `userChrome.js`.
Various API documentation is very scarce, and it is different from general web development.

---

Before introducing JS, I am planning some refactorings in December.

- [ ] SCSS #234
  -  Remove some duplicate code in `userChrome.css`, `userContent.css`
  - Can organize project structure and make code more reusable
  - [csso](https://github.com/css/csso) based optimize
- [ ] Option System #267
  - Adjusted by adding/removing settings to `about:config`
  - Interated [Wiki:Tips](https://github.com/black7375/Firefox-UI-Fix/wiki/Tips)
  - Original, `photon-style`, `proton-style` all the same CSS code

**Comment by black7375** [comment]
I plan to introduce the option system first and then add it as an option.

**Comment by 09dgceph** [comment]
Thank you for your wonderful work on this project. Is there some way I can support it? I don't see a donation link anywhere. 

Also, an installer, whether through WIX/winget/Chocolatey, would be much appreciated. I see it's a "maybe" on the road map. Kamsahamnida!

**Comment by black7375** [comment]
There is currently no public donation method as I signed a contract to prohibit external revenue generation until October of this year.
I feel the need to donate to maintain the project for a long time and to motivate it, and we plan to open it at the end of this year.

Since I've never made a package for WIX/Winget/Chocolately, there is a bit of a learning curve.

**Comment by black7375** [comment]
@mStirner
Try to using options with `v5.0.0`
https://github.com/black7375/Firefox-UI-Fix/wiki/Options#blue-accent-color

**Comment by regs01** [comment]
It would actually be better without Chocolatey bloat. Not everyone needs it, so why pushing it mandatory?
