### ISSUE TITLE
Missing icons on menu bar context menu (Copy Without Site Tracking, Paste and Go)

### ISSUE THREAD

**Issue by happy-dude** [black7375/Firefox-UI-Fix#873]
### Describe the bug

After copying a link and right clicking the menu bar, two options lack corresponding icons:

* Copy Without Site Tracking
* Paste and Go

### Expected behavior

Icons appears for the menu-bar-right-click context menu:

* Copy Without Site Tracking
* Paste and Go

`Copy Without Site Tracking` reuses the same icon from right-clicking a link in a web page

### Screenshots

Right clicking the menu bar after copying a link: 
![Screenshot from 2024-02-20 17-38-42](https://github.com/black7375/Firefox-UI-Fix/assets/1098725/b657a8dc-96e4-4e2e-92d6-01dd80bddf29)

Right clicking a link on a webpage showing an existing `Copy Without Site Tracking` icon:
![Screenshot from 2024-02-20 17-42-19](https://github.com/black7375/Firefox-UI-Fix/assets/1098725/a2f07187-a133-49cd-a88f-bd4272695475)

### OS

Linux

### Firefox Version

125.0a1 20240220094730

### Distribution

- [X] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
- [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
- [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### Theme

- [ ] Light
- [ ] Dark
- [ ] Alpenglow (System: Light)
- [ ] Alpenglow (System: Dark)
- [ ] System Default
- [ ] Others: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

### Theme - More Info

Yaru-dark

### `user.js` setup

<details><summary><strong><code>user.js</code> setup</strong></summary><br>

```javascript
// Your settings
```
</details>

### Additional context

Application Basics
Name 	Firefox
Version 	125.0a1
Build ID 	20240220094730
Distribution ID 	mozilla-deb
Update Channel 	nightly
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
OS 	Linux 6.5.0-1014-oem #15-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 19 11:03:48 UTC 2024
OS Theme 	Yaru-dark / Yaru
Application Binary 	/usr/lib/firefox-nightly/firefox-bin

**Comment by happy-dude** [comment]
I was looking through the code to try and understand what was happening -- perhaps it is found in this file? https://github.com/black7375/Firefox-UI-Fix/blob/d91f2822b4b9f71d6fc7f7d870526fcf56719348/src/icons/context_menu/_others.scss#L142-L158

What can I do to debug further (and maybe contribute a PR)?

**Comment by black7375** [comment]
Yes. If you enable `userChrome.icon.menu.full` as `true` with [`about:config`](https://github.com/black7375/Firefox-UI-Fix/wiki/Tutorial#set-using-aboutconfig), you can have a menu with most of the icons.


`Copy Without Site Tracking` will be empty because it doesn't have an icon yet.

**Comment by happy-dude** [comment]
Ah, thanks for pointing out that setting! This is probably expected behavior then; I'll close this ticket :)
