### ISSUE TITLE
[Suggestion] Future 3.0 roadmap

### ISSUE THREAD

**Issue by 7k5x** [black7375/Firefox-UI-Fix#94]
- [ ] Wiki and README updated to include installer method of un/installation
 - [ ] Seamless support in other *nix systems(FreeBSD, OpenBSD, ReactOS etc)
 - [ ] Use `.ini` file to customize installation
 - [ ] Add Windows installer `.ps1`
 - [ ] Deploy this project to Chocolatey/Scoop
 - [ ] `install.sh` upgraded to have partial installation/full backup support/auto updating and uninstallation
 - [ ] Other current low-priority nice-to-haves and small bug fixes

**Comment by black7375** [comment]
It is scheduled.

>  Add Windows installer .ps1

And there will definitely be improvements to the current installer.
I'm thinking of rewriting a lot of code now that the installer. https://github.com/black7375/Firefox-UI-Fix/pull/61#issuecomment-855180183
In fact, it seems to me that the code now is still a mess and I'm not achieving the coverage I want.

However, we can't just focus on the installer.
It would be more efficient to create an **addon** that notifies you about updates.
To support the nix system, it is right to make it possible to `dash` or `sh` rather than `bash` from the beginning.
It is also not good for general users that the installation process is too granular.

When the version goes up, the product itself should be improved.
The main improvement planned for version 3 is the background color like [Shadowfox](https://overdodactyl.github.io/ShadowFox/).

What I really want to do is enable JS.
Tab preview, battery saver, etc. are possible, and custom settings can be made in settings.
Given more time, the similar feature as [Nyxt](https://nyxt.atlas.engineer/) or [Qutebrowser](https://qutebrowser.org/) would be possible.

**Comment by 7k5x** [comment]
Just as a note, the backslash I added in front of the `mv` and `cp` lines are to avoid the aliases already set to non-force mode.
